global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'springboot-prometheus-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-prometheus-demo:8080']
